# Generated by Django 5.0.6 on 2024-05-21 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Тема мероприятия"),
                ),
                (
                    "program_description",
                    models.TextField(blank=True, verbose_name="Программа"),
                ),
                (
                    "location",
                    models.CharField(max_length=200, verbose_name="Место проведения"),
                ),
                ("start_time", models.DateTimeField(verbose_name="Время начала")),
                ("end_time", models.DateTimeField(verbose_name="Время окончания")),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="image", verbose_name="Изображение"
                    ),
                ),
            ],
            options={
                "verbose_name": "Мероприятие",
                "verbose_name_plural": "мероприятия",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100, verbose_name="ФИО")),
                (
                    "telegram_id",
                    models.PositiveBigIntegerField(
                        unique=True, verbose_name="Внешний ID пользователя"
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Электронная почта"
                    ),
                ),
                (
                    "phonenumber",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Телефон"
                    ),
                ),
                (
                    "company",
                    models.CharField(max_length=200, verbose_name="Работодатель"),
                ),
                (
                    "position",
                    models.CharField(max_length=100, verbose_name="Должность"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("LISTENER", "Слушатель"), ("SPEAKER", "Спикер")],
                        default="LISTENER",
                        max_length=50,
                        verbose_name="Роль",
                    ),
                ),
            ],
            options={
                "verbose_name": "Участник",
                "verbose_name_plural": "Участники",
                "ordering": ["telegram_id"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(verbose_name="Вопрос к спикеру")),
                ("status", models.BooleanField(default=False, verbose_name="Статус")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="telegram_bot.event",
                        verbose_name="Вопрос мероприятия",
                    ),
                ),
                (
                    "listener",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question",
                        to="telegram_bot.user",
                        verbose_name="Вопрос от слушателя",
                    ),
                ),
                (
                    "speaker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answer",
                        to="telegram_bot.user",
                        verbose_name="Ответ спикера",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вопрос",
                "verbose_name_plural": "Вопросы",
                "ordering": ["description"],
            },
        ),
        migrations.CreateModel(
            name="Messages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        max_length=200, verbose_name="Содержание сообщения"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания"
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="message",
                        to="telegram_bot.user",
                        verbose_name="Участники рассылки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "ordering": ["text"],
            },
        ),
        migrations.AddField(
            model_name="event",
            name="speaker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="telegram_bot.user",
                verbose_name="Спикер",
            ),
        ),
    ]
