# Generated by Django 5.0.6 on 2024-05-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("LISTENER", "Слушатель"),
                    ("SPEAKER", "Спикер"),
                    ("MANAGER", "Организатор"),
                ],
                default="LISTENER",
                max_length=50,
                verbose_name="Роль",
            ),
        ),
    ]
