# Generated by Django 5.0.6 on 2024-05-22 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="speaker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="telegram_bot.user",
                verbose_name="Спикер",
            ),
        ),
    ]
