# Generated by Django 5.0.6 on 2024-05-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0003_alter_event_speaker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="company",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Работодатель"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="position",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Должность"
            ),
        ),
    ]
