# Generated by Django 5.0.6 on 2024-05-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0004_alter_user_company_alter_user_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="answer",
            field=models.TextField(blank=True, null=True, verbose_name="Ответ"),
        ),
    ]
